### PR TITLE
Add java-cfenv reconfiguration jar

### PR DESCRIPTION
**Pull request by dyroberts**
- Classic reconfiguration jar remains in its own module
 - New reconfiguration jar...
   - uses java-cfenv to set cloud profile and property source
   - this initial implementation only adds vcap_application properties in 'cloud' property source, not vcap_services, and does not maintain connectors' property naming convention
   - drops bean replacement functionality
   - instead leverages java-cfenv-boot for assorted auto-configuration of bound services
   - had to add the java-cfenv-boot's spring.factories entries to the spring.factories file in this new jar

### CODE REVIEW

**Comment by dyroberts** [comment]
Regarding the lack of a fully populated 'cloud' property source, java-cfenv basic usage has this case covered using SpEL. https://github.com/pivotal-cf/java-cfenv#use-with-spring

**Comment by dyroberts** [comment]
It would be nice to have a cleaner solution to the `spring.factories` file; but I'm not sure what that is. With this implementation, we're stuck updating the file here anytime `java-cfenv-boot`'s version changes.

**Comment by scottfrederick** [comment]
The `cloud` properties provided by Connectors were also confusing w.r.t. their similarity to [Spring Boot's `vcap` properties ](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/cloud/CloudFoundryVcapEnvironmentPostProcessor.html)(which came along after Connectors was introduced). I'm in favor of eliminating the `cloud` properties to reduce this confusion but it could cause pain for users who rely on them currently.

**Comment by scottfrederick** [comment]
> It would be nice to have a cleaner solution to the spring.factories file; but I'm not sure what that is. With this implementation, we're stuck updating the file here anytime java-cfenv-boot's version changes.

Why would this file need to change with `java-cfenv-boot` versions? I don't see anything version-specific in there. 

JBP auto-reconfiguration has always supported an intentionally [limited set of connection types](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration#what-is-auto-reconfiguration), so it wouldn't need to change when new connection types are added to `java-cfenv-boot`.

**Comment by dyroberts** [comment]
Thanks @scottfrederick! I was thinking the same about the cloud property source. Regarding spring.factories file, I just meant that there's the possibility that some java-cfenv version in the future might require an update here. Glad to hear you're ok with this approach.

**Comment by dyroberts** [comment]
@nebhale Any idea when you might have a chance to look at this? :)

**Comment by dmikusa-pivotal** [comment]
Cross-posting here for awareness:  https://github.com/cloudfoundry/java-buildpack/issues/779#issuecomment-1084682829

**Comment by dmikusa-pivotal** [comment]
Closing as we have decided to deprecate & remove auto-configuration versus trying to move forward with it.

**Pull request closed without merging**
