### PR TITLE
Play 2.5.x support

### PR DESCRIPTION
**Pull request by dkowis**
This is a major change to the play support. It will only work with 2.5.x+ (It might work with 2.4.x, I haven't double checked the server api stuff.)

The server API changed and isn't based on NettyServer any longer. Instead you should call the ProdServer object and start it that way. 

This will get support for a play 2.5.x application again on cloud foundry, which will be very helpful. I don't know how to modify this to support multiple versions via configuration....

### CODE REVIEW

**Comment by dkowis** [comment]
This also includes #57, because both are needed to make things cooperate with play-slick and play 2.5.x

**Comment by dkowis** [comment]
Been about a month, I last talked about things on the cloudfoundry slack about some conversations with Lightbend to see if this is the best way to do it. Any progress there?

**Comment by dkowis** [comment]
Notes from conversations on cloudfoundry slack:

Unfortunately this breaks all the tests. Reasoning is this: https://www.playframework.com/documentation/2.5.x/PluginsToModules

Also be sure to remember to run the tests: https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/blob/master/ci/unit-test.sh

**Comment by making** [comment]
Any chance anyone could have a look?

**Comment by nebhale** [comment]
As the auto-reconfiguration support has lagged for Play releases without any real request for keeping up with it, the forth coming 2.x line will drop all support for Play auto-reconfiguration.

I know that you spent a fair amount of time on this, but there just isn't demand from the wider Cloud Foundry community for this.  Sorry about that.

**Comment by dkowis** [comment]
Yeah I understand. Disappointing, but I can't take care of it myself, and that's all right :)

**Pull request closed without merging**
